[package]
name = "gyr-model"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-stream.workspace = true
futures-core.workspace = true
futures-util.workspace = true
gyr-protocol.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
tokio.workspace = true

[lints]
workspace = true
