[package]
name = "gyr-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
futures-util.workspace = true
gyr-model.workspace = true
gyr-protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio-util.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
serde_json.workspace = true
tokio.workspace = true

[lints]
workspace = true
