[package]
name = "gyr-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "gyr"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
gyr-core.workspace = true
gyr-model.workspace = true
gyr-protocol.workspace = true
gyr-tools.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
